import bikeSvg from '../assets/bike.svg'
import activaPng from '../assets/activa.png'
import hunterJpeg from '../assets/Hunter350.jpeg'
import JupiterJpeg from '../assets/Jupiter.jpeg'
import olaJpeg from '../assets/ola.jpeg'
import pulsarJpeg from '../assets/pulsar.jpeg'
import SplendorJpeg from '../assets/splendor.jpeg'

export const BIKES = [
  {
    id: 'b1',
    name: 'Honda Activa 6G',
    brand: 'Honda',
    type: 'Scooter',
    pricePerDay: 299,
    available: true,
    fuelType: 'Petrol',
    mileage: '60 km/l',
    seats: 2,
    year: 2023,
    rating: 4.8,
    reviews: 124,
    description: 'The most trusted scooter for daily gig deliveries. Reliable, fuel-efficient, and easy to maneuver in city traffic.',
    image: activaPng,
    features: ['GPS Tracking', 'USB Charging', 'Anti-lock Brakes', 'Digital Console'],
    color: '#e74c3c',
  },
  {
    id: 'b2',
    name: 'Royal Enfield Hunter 350',
    brand: 'Royal Enfield',
    type: 'Motorcycle',
    pricePerDay: 799,
    available: true,
    fuelType: 'Petrol',
    mileage: '36 km/l',
    seats: 2,
    year: 2023,
    rating: 4.9,
    reviews: 89,
    description: 'A legend reborn. Perfect for intercity gig runs with its powerful engine and premium comfort.',
    image: hunterJpeg,
    features: ['Tripper Navigation', 'Dual Channel ABS', 'USB Charging', 'Side Stand Indicator'],
    color: '#2c3e50',
  },
  {
    id: 'b3',
    name: 'TVS Jupiter 125',
    brand: 'TVS',
    type: 'Scooter',
    pricePerDay: 249,
    available: true,
    fuelType: 'Petrol',
    mileage: '52 km/l',
    seats: 2,
    year: 2024,
    rating: 4.6,
    reviews: 201,
    description: 'Smart and spacious scooter with massive underseat storage. Ideal for food delivery and logistics.',
    image: JupiterJpeg,
    features: ['SmartXonnect App', 'Eco Mode', 'Find My Scooter', 'External Fuel Fill'],
    color: '#8e44ad',
  },
  {
    id: 'b4',
    name: 'Bajaj Pulsar NS200',
    brand: 'Bajaj',
    type: 'Sports',
    pricePerDay: 649,
    available: false,
    fuelType: 'Petrol',
    mileage: '40 km/l',
    seats: 2,
    year: 2023,
    rating: 4.7,
    reviews: 156,
    description: 'High-performance sports bike for the power gig worker. Handles highways and urban grids with equal ease.',
    image: pulsarJpeg,
    features: ['Liquid Cooled Engine', 'Single Channel ABS', 'Backlit Console', 'LED DRL'],
    color: '#e67e22',
  },
  {
    id: 'b5',
    name: 'Ola S1 Pro',
    brand: 'Ola Electric',
    type: 'Electric Scooter',
    pricePerDay: 399,
    available: true,
    fuelType: 'Electric',
    mileage: '181 km/charge',
    seats: 2,
    year: 2024,
    rating: 4.5,
    reviews: 312,
    description: 'Zero emissions, zero fuel costs. The future of gig delivery with massive range and smart connectivity.',
    image: olaJpeg,
    features: ['Move OS 3', 'Reverse Mode', 'Proximity Lock', 'Cruise Control', 'Party Mode'],
    color: '#27ae60',
  },
  {
    id: 'b6',
    name: 'Hero Splendor+',
    brand: 'Hero',
    type: 'Commuter',
    pricePerDay: 199,
    available: true,
    fuelType: 'Petrol',
    mileage: '70 km/l',
    seats: 2,
    year: 2023,
    rating: 4.4,
    reviews: 445,
    description: 'The most economical pick. Legendary fuel efficiency makes it the #1 choice for budget-conscious gig workers.',
    image: SplendorJpeg,
    features: ['i3S Technology', 'Side Stand Indicator', 'USB Mobile Charger', 'Alloy Wheels'],
    color: '#c0392b',
  },
]

export const MOCK_USERS = [
  {
    id: 'u1',
    name: 'Arjun Mehta',
    email: 'arjun@ryde.in',
    password: '123456',
    phone: '+91 98765 43210',
    role: 'user',
    avatar: 'AM',
    joinedAt: '2024-01-15',
  },
  {
    id: 'u2',
    name: 'Admin Ryde',
    email: 'admin@ryde.in',
    password: 'admin123',
    phone: '+91 00000 00000',
    role: 'admin',
    avatar: 'AR',
    joinedAt: '2023-06-01',
  },
]

export const INITIAL_BOOKINGS = [
  {
    id: 'bk1',
    bikeId: 'b2',
    userId: 'u1',
    startDate: '2024-12-01',
    endDate: '2024-12-05',
    status: 'completed',
    totalAmount: 3196,
    bookedAt: '2024-11-28T10:30:00Z',
  },
  {
    id: 'bk2',
    bikeId: 'b1',
    userId: 'u1',
    startDate: '2024-12-20',
    endDate: '2024-12-25',
    status: 'completed',
    totalAmount: 1495,
    bookedAt: '2024-12-18T14:00:00Z',
  },
]

export const FEATURES = [
  {
    icon: '⚡',
    title: 'Instant Activation',
    desc: 'Book in under 60 seconds. No paperwork, no waiting. Your bike is ready when you are.',
    color: '#f97316',
  },
  {
    icon: '🛡️',
    title: 'Full Insurance Cover',
    desc: 'Every rental includes comprehensive insurance. Ride confident, ride protected.',
    color: '#22d3a0',
  },
  {
    icon: '📍',
    title: 'GPS Fleet Tracking',
    desc: 'Real-time location on every vehicle. Safety for riders, peace of mind for operators.',
    color: '#60a5fa',
  },
  {
    icon: '🔧',
    title: '24/7 Roadside Help',
    desc: 'Breakdown on a delivery? We dispatch mechanics within 30 minutes, anywhere in the city.',
    color: '#a78bfa',
  },
  {
    icon: '💳',
    title: 'Weekly Billing',
    desc: 'Flexible payment cycles that match gig payouts. Pay as you earn, not upfront.',
    color: '#f43f5e',
  },
  {
    icon: '📊',
    title: 'Earnings Analytics',
    desc: 'Track your delivery stats, fuel savings, and ROI per bike directly in your dashboard.',
    color: '#fbbf24',
  },
]

export const STATS = [
  { value: '12,000+', label: 'Active Riders', icon: '👥' },
  { value: '₹2.1Cr', label: 'Saved on Fuel', icon: '⛽' },
  { value: '28', label: 'Cities Active', icon: '🏙️' },
  { value: '99.2%', label: 'Uptime SLA', icon: '⚡' },
]

export const TESTIMONIALS = [
  {
    name: 'Kiran Yadav',
    city: 'Bengaluru',
    role: 'Zomato Delivery Partner',
    text: 'Switched to Ryde 6 months ago. My fuel costs dropped 40% with the Ola Electric. The weekly billing fits perfectly with my payout cycle.',
    rating: 5,
    avatar: 'KY',
  },
  {
    name: 'Priya Nair',
    city: 'Mumbai',
    role: 'Dunzo Courier',
    text: 'The Activa is perfect for Mumbai traffic. Never had a breakdown, and the 24/7 support team actually picks up. Recommend to everyone.',
    rating: 5,
    avatar: 'PN',
  },
  {
    name: 'Ravi Kumar',
    city: 'Hyderabad',
    role: 'Blinkit Express',
    text: 'Dashboard shows all my bookings cleanly. Easy to extend, easy to return. This is what gig workers actually needed.',
    rating: 5,
    avatar: 'RK',
  },
]
